# 全局异常中件间

在koa应用中，我们可以通过中间件来捕获异常，保证应用的健壮性，目前没有合适的中间件，我们可以通过自定义中间件来捕获异常，比如：

先自定义一个异常,在`utils/httpException.js`中定义一个异常类

```js
export class HttpException extends Error {
  constructor(msg = '参数错误', errorCode = 10000, code = 400) {
    super()
    this.msg = msg
    this.errorCode = errorCode
    this.code = code
  }
}
```

然后在`middleware/exception.js`中定义一个中间件:

```js
import { HttpException } from "../utils/httpException";
const catchError = async (ctx, next) => {
  try {
    await next();
  } catch (error) {
    // 如果是生产环境，优化错误信息
    if (process.env.NODE_ENV === "production") {
      ctx.status = 500;
      ctx.body = "服务器出错了";
    } else {
      
      if (error instanceof HttpException) {
        // 如果是自定义的错误，则返回自定义的错误信息
        ctx.body = {
          errorMsg: error.msg,
          errorCode: error.errorCode,
          data: null
        }
        ctx.status = error.code
      } else {
        // 如果是未知的错误，则返回未知的错误信息
        throw error;
      }
    }
  }
};

export default catchError;

```

在`src/index.js`中引入中间件:

```js
import catchError from "./middleware/exception";
app.use(catchError);
```
